apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.images.minio }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: console
          args:
            - "server"
            - "/data"
            - "--console-address"
            - ":9001"
          env:
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: minio-mount
              mountPath: /data
      volumes:
        - name: minio-mount
          hostPath:
            path: {{ $.Values.storage.minio.hostPath }}
